Disable compiler warning (only on two files).
These two files have a assert statements that check if an unsigned
integer is greater than or equal to 0, which is always true:

error: comparison of unsigned expression >= 0 is always true
[-Werror,-Wtautological-compare]