Fix expression result unused compiler warning (clang).
The ternary operators in the macro appear to be causing this:

error: expression result unused; should this cast be to 'void'?
[-Werror,-Wunused-value]
  ((void *)sk_set(((_STACK *) (1 ? (ad->sk) : (struct
stack_st_void*)0)), (index), ((void *) (1 ? (val) : (void *)0))));